### ISSUE TITLE
User can view the current weather by typing in the name of a city

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/ajax-project#1]
# 💰 Motivation

A weather app that allows a user to look up the current weather in a city while viewing an historical painting that has a similar vibe and setting.

## 📐 Plan

Create an app that allows user to view the current weather of a city by typing in its name along.

## 🖼️ Wireframe

![Screen Shot 2021-02-22 at 5 29 03 PM](https://user-images.githubusercontent.com/74999873/108791306-9b0c7980-7533-11eb-9a61-c643d16215c4.png)

### ✅ Task List

- [x] Create basic HTML page
- [x]  Add CSS to layout.css to adjust for screen size
- [x] Create header
- [x] Add necessary CSS to match wireframe
- [x] Add image to the body
- [x] Make image randomly generate from API collection
- [x] Ensure that painting title, artist and year is included underneath painting
- [x] Make the background the same painting but at 25% opacity
- [x] Add input box and text 
- [x] add css styling to buttons and input box
- [x] put everything in container with ability to be viewed/hidden
- [x] add back button that will hide page when clicked

**Comment by danielwrosenbaum** [comment]
# 💰 Motivation

A weather app that allows a user to look up the current weather in a city while viewing an historical painting that has a similar vibe and setting.

## 📐 Plan

Create an app that allows user to view the current weather of a city by typing in its name.

## 🖼️ Wireframe

[AJAX Project (1).pdf](https://github.com/danielwrosenbaum/ajax-project/files/6026284/AJAX.Project.1.pdf)


### ✅ Task List

- [ ]
