### ISSUE TITLE
User can view home screen

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/ajax-project#2]
# 💰 Motivation

A weather app that allows a user to look up the current weather in a city while viewing an historical painting that has a similar vibe and setting.

## 📐 Plan

Create a homepage where user can decide to pick between getting weather conditions by city or viewing saved images

## 🖼️ Wireframe

![Screen Shot 2021-02-23 at 12 38 43 PM](https://user-images.githubusercontent.com/74999873/108905080-1e7da780-75d4-11eb-835c-7c4e70773ac1.png)

### ✅ Task List

- [x] create modal that will be positioned over everything at the beginning. 
- [x] add css to make look nice and consistent with Get Weather page
- [x] add image to the background 
- [x] create button for get weather
- [x] create button to view saved images
- [x] add listener event for get weather button to allow to view new screen
- [x] add listener event for view saved images that will take user to new screen
- [x] on get weather page, add functionality to make back button take you to home screen
- [x] fix all errors
- [x] remove any unnecessary CSS
