### ISSUE TITLE
User can view weather

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/ajax-project#3]
# 💰 Motivation

A weather app that allows a user to look up the current weather in a city while viewing an historical painting that has a similar vibe and setting.

## 📐 Plan

When the user types in a city name on the Get Weather page, the current weather conditions for that city will be displayed along with a name painting from the Rijksmuseum.

## 🖼️ Wireframe

![Screen Shot 2021-02-23 at 4 57 45 PM](https://user-images.githubusercontent.com/74999873/108929143-58f93b80-75f8-11eb-8c35-8ee111ca415e.png)

### ✅ Task List

- [x] generate a new HTML from the DOM when user clicks Go! from the get weather page
- [x] update input area on getweather page to make it a form
- [x] add a requirement that text must be entered in textarea before new page will load
- [x] add css and styling to the new page to match wireframe
- [x] add function to get weather from the city user has typed in
- [x] have header change to reflect the current conditions
- [x] add a new image from the painting API when page is loaded
- [x] add a back button to return to Get Weather Page
- [x] add error message if the city name can't be found
