### ISSUE TITLE
Users image will match current weather conditions 

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/ajax-project#4]
# 💰 Motivation

A weather app that allows a user to look up the current weather in a city while viewing an historical painting that has a similar vibe and setting.

## 📐 Plan

Styling and images on the city weather page will match the conditions in the city.

## 🖼️ Wireframe

![Screen Shot 2021-02-23 at 4 57 45 PM](https://user-images.githubusercontent.com/74999873/108929143-58f93b80-75f8-11eb-8c35-8ee111ca415e.png)

### ✅ Task List

- [x] change the color of the heading to reflect various conditions
- [x] add images to reflect various weather conditions to be displayed in weather container along with temperature
- [x] make font color of weather container change to match heading and weather conditions
- [x] add css styling to weather container to make look similar to wireframe
- [x] check that JS code is still running smoothly and reflects changes each time page is reloaded
- [x] make sure that weather data is removed from dom when navigating back to home so that multiple weather/image containers arent viewed at once on weather page
- [x] adjust css layout so background pic always covers entire screen
