### ISSUE TITLE
 User can save images 

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/ajax-project#5]
# 💰 Motivation

A weather app that allows a user to look up the current weather in a city while viewing an historical painting that has a similar vibe and setting.

## 📐 Plan

User will be able to save the images they like to localstorage.

## 🖼️ Wireframe

![Screen Shot 2021-02-23 at 4 57 45 PM](https://user-images.githubusercontent.com/74999873/108929143-58f93b80-75f8-11eb-8c35-8ee111ca415e.png)
![Screen Shot 2021-02-24 at 5 24 21 PM](https://user-images.githubusercontent.com/74999873/109088966-3da83200-76c5-11eb-9380-712442e89ef6.png)

### ✅ Task List

- [x] add save button to main weather screen
- [x] adjust back button on main weather screen so they are spaced evenly at left and right of screen
- [x] add CSS styling so that both buttons match
- [x] add pseudo classes to save button 
- [x] make sure clicking button acknowledges saving image
- [x] add function to gather painting title, artist and url into an object when clicking save
- [x] add code to unshift that object into data.entries and increment the id by 1
- [x] setup localstorage 
- [x] make sure that local storage is saving the requested images and accessing the correct data
