### ISSUE TITLE
User can view saved images

### ISSUE THREAD

**Issue by danielwrosenbaum** [danielwrosenbaum/ajax-project#8]
# 💰 Motivation

A weather app that allows a user to look up the current weather in a city while viewing an historical painting that has a similar vibe and setting.

## 📐 Plan

User will be able to view the images they saved on a separate page

## 🖼️ Wireframe

![Screen Shot 2021-02-25 at 2 45 50 PM](https://user-images.githubusercontent.com/74999873/109229479-35f59580-7778-11eb-8b4a-611653ba3937.png)

### ✅ Task List

- [x] set up function to generate new DOM tree when navigating to the view image page
- [x] style with css to match wireframe
- [x] pull correct data from localstorage to display on page
- [x] make sure that images are removed when navigated away from the page and regenerated when clicking back to view (rather than just adding to each other).
- [x] add ability to click on image and display in a larger container
- [x] make sure that back button will navigate back to homepage 
- [x] add ability to delete a selected image
- [x] fix all errors
- [x] clean up css to make consistent throughout app
